# Generated by Django 5.2.7 on 2026-01-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_material_created_at_material_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('product', 'name')},
        ),
        migrations.AddIndex(
            model_name='specification',
            index=models.Index(fields=['product', 'name'], name='products_sp_product_b3099f_idx'),
        ),
    ]
