# Generated by Django 5.2.7 on 2026-01-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_storeservice_productview_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='final_adjusted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price after negotiation/fulfillment', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_requests', to='products.storeservice'),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('quoted', 'Quote Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed/Fulfilled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
