# Generated by Django 5.2.7 on 2026-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_quotationrequest_final_adjusted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storeservice',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storeservice',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
