# Generated by Django 5.2.7 on 2026-02-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='client_logo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/clients/'),
        ),
    ]
