# Generated by Django 5.2.7 on 2026-01-30 09:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('full_time', 'Full Time Employee'), ('freelancer', 'Freelancer / Project-based')], default='full_time', max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('citizenship_number', models.CharField(blank=True, max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=50)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary for full-time or rate for freelancers', max_digits=10)),
                ('citizenship_front', models.ImageField(blank=True, null=True, upload_to='staff/docs/')),
                ('citizenship_back', models.ImageField(blank=True, null=True, upload_to='staff/docs/')),
                ('insurance_doc', models.FileField(blank=True, null=True, upload_to='staff/docs/')),
                ('contract_doc', models.FileField(blank=True, null=True, upload_to='staff/docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('year', models.IntegerField()),
                ('calculated_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='hr.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.staffprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
