# Generated by Django 5.2.7 on 2026-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff/profiles/'),
        ),
    ]
